FROM golang:alpine as builder
RUN apk --no-cache add git
WORKDIR /app
COPY . .
RUN GOOS=linux go build -ldflags "-s -w" -o static-server cli/static-server/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
RUN mkdir -p /app/static
WORKDIR /app
COPY --from=builder /app/static-server .
COPY --from=builder /app/cli/static-server/static static
EXPOSE 3000
ENTRYPOINT ["./static-server", "-mode", "prod", "-addr", "0.0.0.0:3000"]