FROM golang:alpine as builder
RUN apk --no-cache add git
WORKDIR /app
COPY . .
RUN GOOS=linux go build -ldflags "-s -w" -o service cli/service/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
RUN mkdir -p /app/migrations
WORKDIR /app
COPY --from=builder /app/service .
COPY --from=builder /app/migrations migrations
COPY --from=builder /app/wait-for-it.sh .
# EXPOSE 50051
# ENTRYPOINT ["./service", "-mode", "prod", "-addr", "0.0.0.0:50051"]